/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Luis Diego
 */
public class RegistroCerveza extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCerveza
     */
    public RegistroCerveza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_Descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        TF_Descripcion1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TF_Descripcion2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        TF_Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_DescripcionActionPerformed(evt);
            }
        });
        add(TF_Descripcion);
        TF_Descripcion.setBounds(200, 430, 120, 20);

        jLabel1.setText("Descripción");
        add(jLabel1);
        jLabel1.setBounds(80, 60, 70, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(200, 100, 160, 20);

        jLabel2.setText("Cuerpo");
        add(jLabel2);
        jLabel2.setBounds(80, 100, 70, 20);

        jLabel3.setText("Color");
        add(jLabel3);
        jLabel3.setBounds(80, 150, 70, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(200, 150, 160, 20);

        jLabel4.setText("Fermentación: ");
        add(jLabel4);
        jLabel4.setBounds(80, 200, 87, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(200, 200, 160, 20);

        jLabel5.setText("Estilo: ");
        add(jLabel5);
        jLabel5.setBounds(80, 250, 87, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4);
        jComboBox4.setBounds(200, 250, 160, 20);

        jLabel6.setText("Familia: ");
        add(jLabel6);
        jLabel6.setBounds(80, 310, 87, 14);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5);
        jComboBox5.setBounds(200, 300, 160, 20);

        jLabel7.setText("Precio:   ");
        add(jLabel7);
        jLabel7.setBounds(80, 430, 87, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox6);
        jComboBox6.setBounds(200, 350, 160, 20);

        TF_Descripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Descripcion1ActionPerformed(evt);
            }
        });
        add(TF_Descripcion1);
        TF_Descripcion1.setBounds(200, 50, 164, 20);

        jLabel8.setText("Tipo: ");
        add(jLabel8);
        jLabel8.setBounds(80, 360, 87, 14);

        jLabel9.setText("Temperatura: ");
        add(jLabel9);
        jLabel9.setBounds(80, 390, 87, 14);

        TF_Descripcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Descripcion2ActionPerformed(evt);
            }
        });
        add(TF_Descripcion2);
        TF_Descripcion2.setBounds(200, 390, 140, 20);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(560, 230, 120, 50);

        jButton2.setText("Agregar");
        add(jButton2);
        jButton2.setBounds(560, 150, 120, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_DescripcionActionPerformed

    private void TF_Descripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Descripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Descripcion1ActionPerformed

    private void TF_Descripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Descripcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Descripcion2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_Descripcion;
    private javax.swing.JTextField TF_Descripcion1;
    private javax.swing.JTextField TF_Descripcion2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
