/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registro;

/**
 *
 * @author Luis Diego
 */
public class RegistroCerveza extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCerveza
     */
    public RegistroCerveza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TF_Descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<String>();
        TF_Descripcion1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TF_Descripcion2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TF_Descripcion3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setLayout(null);

        TF_Descripcion.setBackground(new java.awt.Color(217, 217, 148));
        TF_Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_DescripcionActionPerformed(evt);
            }
        });
        add(TF_Descripcion);
        TF_Descripcion.setBounds(200, 440, 340, 60);

        jLabel1.setText("Nombre");
        add(jLabel1);
        jLabel1.setBounds(80, 70, 70, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(200, 110, 160, 20);

        jLabel2.setText("Cuerpo");
        add(jLabel2);
        jLabel2.setBounds(80, 110, 70, 20);

        jLabel3.setText("Color");
        add(jLabel3);
        jLabel3.setBounds(80, 160, 70, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(200, 160, 160, 20);

        jLabel4.setText("Fermentación: ");
        add(jLabel4);
        jLabel4.setBounds(80, 210, 87, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3);
        jComboBox3.setBounds(200, 210, 160, 20);

        jLabel5.setText("Estilo: ");
        add(jLabel5);
        jLabel5.setBounds(80, 260, 87, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4);
        jComboBox4.setBounds(200, 260, 160, 20);

        jLabel6.setText("Familia: ");
        add(jLabel6);
        jLabel6.setBounds(80, 320, 87, 14);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox5);
        jComboBox5.setBounds(200, 310, 160, 20);

        jLabel7.setText("Descripcion:");
        add(jLabel7);
        jLabel7.setBounds(80, 440, 87, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox6);
        jComboBox6.setBounds(200, 360, 160, 20);

        TF_Descripcion1.setBackground(new java.awt.Color(217, 217, 148));
        TF_Descripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Descripcion1ActionPerformed(evt);
            }
        });
        add(TF_Descripcion1);
        TF_Descripcion1.setBounds(200, 60, 164, 20);

        jLabel8.setText("Tipo: ");
        add(jLabel8);
        jLabel8.setBounds(80, 370, 87, 14);

        jLabel9.setText("Temperatura: ");
        add(jLabel9);
        jLabel9.setBounds(80, 400, 87, 14);

        TF_Descripcion2.setBackground(new java.awt.Color(217, 217, 148));
        TF_Descripcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Descripcion2ActionPerformed(evt);
            }
        });
        add(TF_Descripcion2);
        TF_Descripcion2.setBounds(200, 400, 140, 20);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(560, 240, 120, 50);

        jButton2.setText("Agregar");
        add(jButton2);
        jButton2.setBounds(560, 160, 120, 50);

        jButton3.setText("Otro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(380, 110, 80, 23);

        jButton4.setText("Otro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(380, 210, 80, 23);

        jButton5.setText("Otro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(380, 260, 80, 23);

        jButton6.setText("Otro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(380, 310, 80, 23);

        jButton7.setText("Otro");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(380, 360, 80, 23);

        jButton8.setText("Otro");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(380, 160, 80, 23);

        jLabel10.setText("Precio:   ");
        add(jLabel10);
        jLabel10.setBounds(380, 400, 87, 14);

        TF_Descripcion3.setBackground(new java.awt.Color(217, 217, 148));
        TF_Descripcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Descripcion3ActionPerformed(evt);
            }
        });
        add(TF_Descripcion3);
        TF_Descripcion3.setBounds(450, 400, 120, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Registro Cerveza");
        add(jLabel11);
        jLabel11.setBounds(280, 20, 180, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_DescripcionActionPerformed

    private void TF_Descripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Descripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Descripcion1ActionPerformed

    private void TF_Descripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Descripcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Descripcion2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Registro.RegistroCuerpo2().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Registro.RegistroFermentacion().setVisible(true);        
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Registro.RegistroEstilo().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Registro.RegistroTipo().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Registro.RegistroColor().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void TF_Descripcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Descripcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_Descripcion3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Registro.RegistroFamilia().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_Descripcion;
    private javax.swing.JTextField TF_Descripcion1;
    private javax.swing.JTextField TF_Descripcion2;
    private javax.swing.JTextField TF_Descripcion3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables


}
