/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registro;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Diego
 */
public class RegistroProvincia extends javax.swing.JPanel {
    ArrayList llave= new ArrayList();

    /**
     * Creates new form RegistroFermentacion
     */
    public RegistroProvincia() {
        initComponents();
        llenarpais();
    }
    public final  void llenarpais() {
        jComboBox1.removeAllItems();
        llave.clear();
            try {
            Connection con = proyectocerveza.dbConnection.conectDB();
                Statement cstmt = con.createStatement();
                ResultSet rs = cstmt.executeQuery("call getPais");
                while(rs.next()){
                   llave.add(rs.getInt(1));
                   jComboBox1.addItem(rs.getString("Descripción"));
                }
                
            } catch (SQLException ex) {
               
            }
    }
    public void InsertProvincia(){
        Connection con= null;
            String puesto=jTextField1.getText();
            con= proyectocerveza.dbConnection.conectDB();
            try {
                int id_pais=(int) llave.get(jComboBox1.getSelectedIndex());
                CallableStatement proc= con.prepareCall("{call insertProvincia(?,?)}");
                proc.setInt(2, id_pais);
                proc.setString(1,puesto);
                proc.execute();
                JOptionPane.showMessageDialog(this, "Provincia Agregada Exitosamente",null,JOptionPane.INFORMATION_MESSAGE);
                jTextField1.setText("");
                con.close();
                
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this, "Error:"+ex,null,JOptionPane.ERROR_MESSAGE);

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setLayout(null);

        jTextField1.setBackground(new java.awt.Color(217, 217, 148));
        add(jTextField1);
        jTextField1.setBounds(290, 210, 225, 31);

        jLabel1.setText("Pais: ");
        add(jLabel1);
        jLabel1.setBounds(160, 140, 74, 31);

        jLabel2.setText("Provincia: ");
        add(jLabel2);
        jLabel2.setBounds(160, 220, 80, 20);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(160, 360, 120, 50);

        jButton2.setText("Modificar");
        add(jButton2);
        jButton2.setBounds(330, 360, 130, 50);

        jButton3.setText("Eliminar");
        add(jButton3);
        jButton3.setBounds(510, 360, 130, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Registro Provincia");
        add(jLabel12);
        jLabel12.setBounds(320, 50, 180, 22);

        add(jComboBox1);
        jComboBox1.setBounds(290, 140, 230, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Debe de llenar todos los campos obligatorios.",null,JOptionPane.ERROR_MESSAGE); 
        }
        else{
            InsertProvincia();   
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
