/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estadisticas;

import Consultas.*;
import Registro.*;

/**
 *
 * @author Luis Diego
 */
public class EstadisticaEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form RegistroFermentacion
     */
    public EstadisticaEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BT_Analizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Consulta Empleados");
        add(jLabel11);
        jLabel11.setBounds(320, 50, 180, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre: ");
        add(jLabel2);
        jLabel2.setBounds(110, 270, 80, 20);

        BT_Analizar.setText("Analizar");
        BT_Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AnalizarActionPerformed(evt);
            }
        });
        add(BT_Analizar);
        BT_Analizar.setBounds(520, 270, 110, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad de personas:");
        add(jLabel3);
        jLabel3.setBounds(110, 320, 140, 14);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 255, 153));
        add(jTextField1);
        jTextField1.setBounds(270, 320, 40, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "País", "Provincia", "Cantón", "Distrito" }));
        add(jComboBox1);
        jComboBox1.setBounds(220, 230, 90, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Analizar por: ");
        add(jLabel1);
        jLabel1.setBounds(110, 230, 100, 14);

        jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(190, 270, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total de empleados:");
        add(jLabel4);
        jLabel4.setBounds(300, 110, 140, 15);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(153, 255, 153));
        add(jTextField3);
        jTextField3.setBounds(460, 110, 40, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void BT_AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AnalizarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BT_AnalizarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Analizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
